camera:
  connection:
    ip: 192.168.1.101
    port: 2122
    protocol: Cola2
    timeout: 10
  enabled: false
  type: SICK
logging:
  console:
    enabled: true
    format: '[{time:YYYY-MM-DD HH:mm:ss}] {level} | {name} | {message}'
  enabled: true
  file:
    backup_count: 30
    enabled: true
    filename: sickvision_{date}.log
    max_size: 10MB
    path: logs
    rotation: daily
  level: INFO
  loggers:
  - level: INFO
    name: VisionCore
  - level: DEBUG
    name: ConfigManager
  - level: INFO
    name: MQTT
  - level: INFO
    name: API
  - level: INFO
    name: TcpServer
mqtt:
  connection:
    broker_host: localhost
    broker_port: 1883
    client_id: sickvision_headless
    keepalive: 60
    password: ''
    use_ssl: false
    username: ''
  enabled: true
  message:
    compression: false
    max_payload_size: 1048576
    retain: false
  qos:
    publish: 2
    subscribe: 2
  topics:
    publish:
      config_reload_response: sickvision/config/reload/response
      control_status: sickvision/control/status
      detection_result: sickvision/detection/result
      system_error: sickvision/system/error
      system_heartbeat: sickvision/system/heartbeat
      system_status: sickvision/system/status
    subscribe:
      config_update: sickvision/config/update
      control_start: sickvision/control/start
      control_stop: sickvision/control/stop
      detection_trigger: sickvision/detection/trigger
      system_command: sickvision/system/command
system:
  debug: false
  log_level: INFO
  max_workers: 4
  name: SickVision-Headless
  version: 1.0.0
tcp_server:
  buffer_size: 4096
  connection_timeout: 300
  enabled: true
  heartbeat_interval: 30
  host: 0.0.0.0
  keep_alive: true
  max_connections: 15
  message:
    encoding: utf-8
    max_size: 1048576
  port: 9999
  socket_timeout: 5
