board_mode:
  enabled: true
  infinite_retry: true
  monitoring:
    check_interval: 30
    failure_threshold: 2
  retry_delay: 5
camera:
  connection:
    ip: 192.168.2.10
    port: 2122
    protocol: Cola2
    timeout: 10
  enabled: true
  type: SICK
detectionServer:
  buffer_size: 4096
  connection_timeout: 300
  enabled: true
  heartbeat_interval: 30
  host: 192.168.2.20
  keep_alive: true
  max_connections: 15
  message:
    encoding: utf-8
    max_size: 1048576
  port: 8888
  socket_timeout: 5
logging:
  console:
    enabled: true
    format: '[{time:YYYY-MM-DD HH:mm:ss}] {level} | {name} | {message}'
  enabled: true
  file:
    backup_count: 30
    enabled: true
    filename: sickvision_{date}.log
    max_size: 10MB
    path: logs
    rotation: daily
  level: INFO
  loggers:
  - level: INFO
    name: VisionCore
  - level: DEBUG
    name: ConfigManager
  - level: INFO
    name: MQTT
  - level: INFO
    name: API
  - level: INFO
    name: TcpServer
model:
  availableModels:
  - obb_seasoning256.float.rknn
  - seasoning256.pt
  selectedModel: seasoning256.pt
mqtt:
  connection:
    broker_host: 127.0.0.1
    broker_port: 1883
    client_id: sickvision_headless
    keepalive: 60
    password: ''
    use_ssl: false
    username: ''
  enabled: true
  message:
    compression: false
    max_payload_size: 1048576
    retain: false
  qos:
    publish: 2
    subscribe: 2
  topics:
    publish:
      message: PI/robot/message
    subscribe:
      system_command: sickvision/system/command
roi:
  centerXOffset: 25
  centerYOffset: 50
  enable: true
  height: 120
  width: 120
sftp:
  connection:
    retry_attempts: 3
    timeout: 15
  enabled: true
  host: 192.168.2.20
  password: '123456'
  port: 22
  remote_path: /
  upload:
    create_directories: true
    overwrite_existing: true
    verify_checksum: true
  username: qt
detection:
  saveImage:
    enabled: true                    # 是否启用图像保存功能
    directory: "./saved_images"      # 图像保存目录
    uploadToSftp: false              # 是否上传到SFTP服务器
    autoCleanup: true                # 是否自动清理旧文件
    maxFiles: 100                    # 最大保存文件数量
    quality: 95                      # JPEG质量 (1-100)
stability:
  detectionCount: 1            # 单步模式下只需要检测1次
  isEnabled: false             # 单步模式下禁用稳定性检测
  pixelThreshold: 5.0          # 稳定性检测的像素阈值（单步模式下不使用）
  debounceTime: 2.0            # TCP防抖时间（秒）
  zOffset: 0             # Z坐标补偿值
system:
  debug: false
  log_level: INFO
  max_workers: 4
  name: SickVision-Headless
  version: 1.0.0
