system:
  name: SickVision-Headless
  version: 1.0.0
  debug: false
  log_level: INFO
  max_workers: 4
camera:
  enabled: false
  type: SICK
  connection:
    ip: 192.168.1.101
    port: 2122
    timeout: 10
    protocol: Cola2
mqtt:
  enabled: true
  connection:
    broker_host: localhost
    broker_port: 1883
    keepalive: 60
    client_id: sickvision_headless
    username: ''
    password: ''
    use_ssl: false
  qos:
    subscribe: 2
    publish: 2
  topics:
    subscribe:
      config_update: sickvision/config/update
      control_start: sickvision/control/start
      control_stop: sickvision/control/stop
      detection_trigger: sickvision/detection/trigger
      system_command: sickvision/system/command
    publish:
      config_reload_response: sickvision/config/reload/response
      control_status: sickvision/control/status
      detection_result: sickvision/detection/result
      system_heartbeat: sickvision/system/heartbeat
      system_error: sickvision/system/error
      system_status: sickvision/system/status
  message:
    retain: false
    compression: false
    max_payload_size: 1048576
logging:
  enabled: true
  level: INFO
  file:
    enabled: true
    path: logs
    filename: sickvision_{date}.log
    max_size: 10MB
    backup_count: 30
    rotation: daily
  console:
    enabled: true
    format: '[{time:YYYY-MM-DD HH:mm:ss}] {level} | {name} | {message}'
  loggers:
  - name: VisionCore
    level: INFO
  - name: ConfigManager
    level: DEBUG
  - name: MQTT
    level: INFO
  - name: API
    level: INFO
